#!/usr//bin/php -f
<?

  require("scripts/conn.php");

  $sql = "Select id_usuario, nome, email from usuario where id_usuario = 12";
  $result = mysql_query($sql);

  $now = date("G:i:s") ;

  $agora = mktime( date("G"), date("i"), date("s"), date("m"), date("d"), date("Y"),1 );
  $soma1dia = mktime(-2, 0, 0,  1, 2, 1970);
  $amanha = date("Y-m-d",$agora+$soma1dia);
  $data = date("d/m/Y", $agora+$soma1dia) ;

  $headers  = "MIME-Version: 1.0\n";
  $headers .= "Content-type: text/html; charset=utf-8\n";
  $headers .= "From: Agenda Datamace<agenda@datamace.com.br>\n";

  $subject = "Compromisso $data";
  $textEmail = '<style type="text/css">';
  $textEmail .= '<!-- a:hover {color: #FF0000;text-decoration: underline;}a {	color: #003366;	text-decoration: none;}--></style>';
  $textEmail .= '<font size="2" face="Verdana, Arial, Helvetica, sans-serif"><a href="http://10.1.0.1/agenda/"><img src="http://10.1.0.1/agenda/figuras/icone_calendario.JPG" width="55" height="55" border="0">Agenda corporativa Datamace</a><br><br>';
  $textEmail .= "Você tem compromisso(s) para amanhã ($data)<br><br>";
  $textEmail .= "</font>";

die($textEmail);

  while ($linha=mysql_fetch_object($result)) {

    $compromissos = "";
    $emailpadrao =  $linha->email;

    $sql2 = "select  data, resumo, hora, horafim from usuario, compromisso, ";
    $sql2 .= "compromissousuario where ";
	$sql2 .= "compromisso.excluido=0 and ";
	$sql2 .= "compromissousuario.id_usuario=usuario.id_usuario and ";
    $sql2 .= "compromisso.id=compromissousuario.id_compromisso and ";
	$sql2 .= "usuario.id_usuario = " . $linha->id_usuario;
    $sql2 .= " and data = '$amanha'" ;
    $sql2 .= " order by hora ";
    $result2 = mysql_query($sql2);

	if (mysql_affected_rows() > 0 ) { 	// se o cara tem compromisso:

	$compromissos .= '<table width="400" border="0" cellpadding="1" cellspacing="1" bgcolor="#CCCCCC"><tr bgcolor="#003366"> ';
	$compromissos .= '<td width="20%"><strong><font color="#FFFFFF" size="2" face="Tahoma">Hora</font></strong></td>';
	$compromissos .= '<td width="61%"><strong><font color="#FFFFFF" size="2" face="Tahoma">Resumo</font></strong></td>';
      while ($linha2=mysql_fetch_object($result2)) {
		$compromissos .= '  </tr><tr bgcolor="#FFFFFF"> ';
		$compromissos .= "    <td><font size=2 face=Tahoma>$linha2->hora</font></td>";
		$compromissos .= "    <td><font size=\"2\" face=\"Tahoma\">$linha2->resumo</font></td>";
		$compromissos .= '  </tr>';
	  }
      $compromissos .= "</table>";
      mail2($emailpadrao, $subject, $textEmail.$compromissos, $headers);
	}
  }
?>
